[package]
name = "egui_extras_datepicker_fork"
edition = "2021"
version = "0.31.0"

[dependencies]
egui = "0.31"
egui_extras = "0.31" 
chrono = { version = "0.4", default-features = false, features = [
  "clock",
  "std",
] }
